### ISSUE TITLE
Cant use in a LAN server 

### ISSUE THREAD

**Issue by glate7** [0XDE57/AssaultCubeHack#6]
Idk if its a bug but i tried to use this in a LAN server with a friend and it not worked (esp + aimbot )

**Comment by ctrlsam** [comment]
Seems to work fine for me

**Comment by glate7** [comment]
Ow ok, thanks for your reply I will try again.

Le mar. 9 avr. 2019 à 03:52, Sam Redmond <notifications@github.com> a
écrit :
