### ISSUE TITLE
How to insert it with Mac OS

### ISSUE THREAD

**Issue by XxanimeboyxXYT** [0XDE57/AssaultCubeHack#8]
How do you insert the scripts using a mac? This looks interesting to hack, and I don't have a computer that has windows that really sucks.

**Comment by ghost** [comment]
This wont work with Mac because it is using windows API directly, see https://github.com/0XDE57/AssaultCubeHack/blob/master/AssaultCubeHack/util/NativeMethods.cs

This is exposing windows API and using it directly, so no way this will work on mac.

**Comment by 0xDE57** [comment]
macos not supported.
